version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - movie-app
      
  server:
    container_name: server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - movie-app

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - movie-app
    volumes:
      - mongo-data:/data/db

networks:
  movie-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local